# Generated by Django 3.0.7 on 2020-06-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateTimeField(verbose_name='Дата митапа'),
        ),
    ]
