# Generated by Django 3.0.7 on 2020-06-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_site', '0002_auto_20200627_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_number',
        ),
        migrations.RemoveField(
            model_name='post',
            name='speaker',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=100, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-06-29', verbose_name='Обновлено'),
            preserve_default=False,
        ),
    ]
